package ve.edu.uc.protys.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import ve.edu.uc.protys.dto.StandardIncorporationResult;
import ve.edu.uc.protys.model.AlignmentRule;
import ve.edu.uc.protys.service.StandardIncorporationService;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@Slf4j
@RestController
@RequestMapping("/api/wizard")
@Tag(name = "Standard Incorporation Wizard", description = "Multi-step wizard for standard ontology incorporation")
@RequiredArgsConstructor
public class StandardWizardController {

    private final StandardIncorporationService standardIncorporationService;

    // Step 1: Upload Standard Ontology

    @PostMapping("/step1/upload")
    @Operation(summary = "Step 1: Upload standard ontology", description = "Upload a new standard OWL file to be incorporated")
    public ResponseEntity<StandardIncorporationResult> uploadStandardOntology(
            @RequestParam("file") MultipartFile file,
            @RequestParam("standardName") String standardName) {
        log.info("Step 1: Uploading standard ontology - {}", standardName);
        try {
            if (file.isEmpty()) {
                log.warn("Empty file upload attempted");
                return ResponseEntity.badRequest().build();
            }

            if (!isValidOwlFile(file.getOriginalFilename())) {
                log.warn("Invalid file type: {}", file.getOriginalFilename());
                return ResponseEntity.badRequest().build();
            }

            StandardIncorporationResult uploadResult = standardIncorporationService.step1_upload(file, standardName);
            UUID tempId = uploadResult.getTempModuleId();

            log.info("Standard ontology uploaded successfully with tempId: {}", tempId);
            return ResponseEntity.status(HttpStatus.CREATED).body(uploadResult);
        } catch (Exception e) {
            log.error("Error uploading standard ontology", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    // Step 2: Validate Consistency

    @PostMapping("/step2/validate/{tempId}")
    @Operation(summary = "Step 2: Validate consistency", description = "Validate the consistency and completeness of the uploaded standard ontology")
    public ResponseEntity<StandardIncorporationResult> validateConsistency(@PathVariable UUID tempId) {
        log.info("Step 2: Validating consistency for tempId: {}", tempId);
        try {
            StandardIncorporationResult validationResult = standardIncorporationService.step2_validateConsistency(tempId);
            boolean isConsistent = Boolean.TRUE.equals(validationResult.getStep2_consistent());

            if (!isConsistent) {
                log.warn("Consistency validation failed for tempId: {}", tempId);
                return ResponseEntity.ok(validationResult);
            }

            log.info("Consistency validation passed");
            return ResponseEntity.ok(validationResult);
        } catch (Exception e) {
            log.error("Error validating consistency", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    // Step 3: Define Alignment Rules

    @PostMapping("/step3/alignments/{tempId}")
    @Operation(summary = "Step 3: Define alignment rules", description = "Define SWRL alignment rules between the standard and existing ontology")
    public ResponseEntity<StandardIncorporationResult> defineAlignmentRules(
            @PathVariable UUID tempId,
            @RequestBody List<AlignmentRule> rules) {
        log.info("Step 3: Defining {} alignment rules for tempId: {}", rules.size(), tempId);
        try {
            if (rules == null || rules.isEmpty()) {
                log.warn("Invalid alignment data: missing rules");
                return ResponseEntity.badRequest().build();
            }

            StandardIncorporationResult alignmentResult = standardIncorporationService.step3_defineAlignments(tempId, rules);

            log.info("Alignment rules defined successfully");
            return ResponseEntity.ok(alignmentResult);
        } catch (Exception e) {
            log.error("Error defining alignment rules", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    // Step 4: Verify Inferences

    @PostMapping("/step4/verify/{tempId}")
    @Operation(summary = "Step 4: Verify inferences", description = "Execute reasoning to verify inferences generated by the alignment rules")
    public ResponseEntity<StandardIncorporationResult> verifyInferences(@PathVariable UUID tempId) {
        log.info("Step 4: Verifying inferences for tempId: {}", tempId);
        try {
            StandardIncorporationResult verificationResult = standardIncorporationService.step4_verifyInferences(tempId);

            log.info("Inference verification completed successfully");
            return ResponseEntity.ok(verificationResult);
        } catch (Exception e) {
            log.error("Error verifying inferences", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    // Step 5: Complete Incorporation

    @PostMapping("/complete/{tempId}")
    @Operation(summary = "Step 5: Complete incorporation", description = "Finalize the standard incorporation and commit all changes to the main ontology")
    public ResponseEntity<StandardIncorporationResult> completeIncorporation(@PathVariable UUID tempId) {
        log.info("Step 5: Completing standard incorporation for tempId: {}", tempId);
        try {
            StandardIncorporationResult completionResult = standardIncorporationService.completeIncorporation(tempId);

            log.info("Standard incorporation completed successfully with finalModuleId: {}", completionResult.getFinalModuleId());
            return ResponseEntity.status(HttpStatus.CREATED).body(completionResult);
        } catch (Exception e) {
            log.error("Error completing incorporation", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    // Helper Methods

    private boolean isValidOwlFile(String filename) {
        return filename != null && (filename.endsWith(".owl") ||
                filename.endsWith(".rdf") ||
                filename.endsWith(".ttl"));
    }
}
