"""Independent, directed checks for the four human-approved contracts."""
from build_catalog import QUERIES, ADDITIONAL_CONTROLS
from numeric_contract import AMBIGUOUS, INPUT_INVALID, OUTPUT_INVALID

def append_cases(ttl, assertion, tests, tbox, qbody):
 def isolated(name,body,check,expected=True,rules='NONE',**opts):
  path=ttl(name,body)
  assertion(name,check,expected,files=tbox+[path],enabled_rules=rules,**opts)
  return path
 threshold='''f:T a owl:NamedIndividual, t:ThresholdRecord ; t:thresholdValue "5"^^xsd:decimal ; t:thresholdUnit "kg CO2e"^^xsd:string ; t:thresholdCategory "GHG_ELECTRICITY_PRODUCTION"^^xsd:string .'''
 indicator='''f:I a owl:NamedIndividual, e:ImpactIndicator ; e:hasIndicatorValue "6"^^xsd:decimal ; t:unit "kg CO2e"^^xsd:string ; t:indicatorCategory "GHG_ELECTRICITY_PRODUCTION"^^xsd:string ; t:hasThreshold f:T .'''
 cases=[('above',indicator+threshold,True),('equal',indicator.replace('"6"','"5"')+threshold,False),('below',indicator.replace('"6"','"4"')+threshold,False),('zero',indicator.replace('"6"','"0"')+threshold,False),('wrong_unit',indicator.replace('t:unit "kg CO2e"','t:unit "L"')+threshold,False),('wrong_category',indicator.replace('t:indicatorCategory "GHG_ELECTRICITY_PRODUCTION"','t:indicatorCategory "WATER_USE"')+threshold,False),('missing_indicator_unit',indicator.replace('t:unit "kg CO2e"^^xsd:string ; ','')+threshold,False),('missing_indicator_category',indicator.replace('t:indicatorCategory "GHG_ELECTRICITY_PRODUCTION"^^xsd:string ; ','')+threshold,False),('missing_threshold_value',indicator+threshold.replace('t:thresholdValue "5"^^xsd:decimal ; ',''),False),('missing_threshold_unit',indicator+threshold.replace('t:thresholdUnit "kg CO2e"^^xsd:string ; ',''),False),('missing_threshold_category',indicator+threshold.replace(' ; t:thresholdCategory "GHG_ELECTRICITY_PRODUCTION"^^xsd:string',''),False),('unlinked_record',indicator.replace(' ; t:hasThreshold f:T','')+threshold,False),('numeric_equivalent_threshold',indicator+threshold+' f:T t:thresholdValue "5.0"^^xsd:decimal .',True)]
 for name,body,expected in cases:
  isolated('R04_contract_'+name,body,'f:I a c:HighImpactIndicator .',expected,['R04'],mechanism='R04',case='Threshold tuple on same record IRI; same indicator unit/category and strict > boundary')
 cross=indicator.replace('t:hasThreshold f:T','t:hasThreshold f:T, f:OtherT')+threshold.replace('t:thresholdUnit "kg CO2e"','t:thresholdUnit "L"')+''' f:OtherT a owl:NamedIndividual, t:ThresholdRecord ; t:thresholdValue "500"^^xsd:decimal ; t:thresholdUnit "kg CO2e"^^xsd:string ; t:thresholdCategory "GHG_ELECTRICITY_PRODUCTION"^^xsd:string .'''
 isolated('R04_contract_coupled_records',cross,'f:I a c:HighImpactIndicator .',False,['R04'],case='Cannot combine low value of one threshold record with unit of another')
 path=ttl('R04-contract-contradictory-threshold',indicator+threshold+' f:T t:thresholdValue "6"^^xsd:decimal .')
 tests.append(dict(id='R04_contract_contradictory_threshold',configuration='integrated',files=tbox+[path],enabled_rules=['R04'],expected_status='INCONSISTENT',case='Threshold value is functional: unequal values contradict OWL, not a successful classification'))
 hotspot=indicator.replace(' ; t:unit "kg CO2e"^^xsd:string',' ; t:unit "L"^^xsd:string')+threshold+''' f:I e:computedForProcess f:LCI . f:LCI a owl:NamedIndividual, e:UnitProcess . f:P a owl:NamedIndividual, i:ManufacturingProcess ; t:hasInventoryRepresentation f:LCI . f:O a owl:NamedIndividual, i:ProcessOperation ; i:partOfProcess f:P ; i:requiresResource f:M . f:M a owl:NamedIndividual, c:BottleneckResource .'''
 isolated('R22_wrong_indicator_unit',hotspot,'f:M a c:Hotspot .',False,['R04','R22'],case='An incompatible R04 threshold cannot seed R22 hotspot classification')
 maintenance='f:M a owl:NamedIndividual, i:ManufacturingResource ; i:hasMaintenance f:Record . f:Record a owl:NamedIndividual . '
 for name,status,expected in [('active','ACTIVE',True),('planned','PLANNED',False),('completed','COMPLETED',False),('missing',None,False)]:
  isolated('R15_contract_'+name,maintenance+('f:Record t:maintenanceStatus "'+status+'"^^xsd:string .' if status else ''),'f:M a i:temporarilyUnavailable .',expected,['R15'],case='Only declared ACTIVE maintenance in this snapshot implies temporary unavailability; no date-based inference')
 isolated('R15_contract_unlinked_active',maintenance+' f:OtherRecord a owl:NamedIndividual ; t:maintenanceStatus "ACTIVE"^^xsd:string .','f:M a i:temporarilyUnavailable .',False,['R15'],case='Unlinked active record cannot mark this resource')
 isolated('R15_contract_other_resource_active',maintenance+' f:OtherMachine a owl:NamedIndividual, i:ManufacturingResource ; i:hasMaintenance f:ActiveRecord . f:ActiveRecord a owl:NamedIndividual ; t:maintenanceStatus "ACTIVE"^^xsd:string .','f:M a i:temporarilyUnavailable .',False,['R15'],case='Active maintenance belongs to another resource')
 base='''f:NLot a owl:NamedIndividual, i:Lot ; i:hasProcess f:NP ; i:hasActivity f:NO ; t:producesProduct f:NPaint ; i:functionalUnit "L"^^xsd:string ; i:producesQuantity "100"^^xsd:decimal .
f:NP a owl:NamedIndividual, i:ManufacturingProcess . f:NPaint a owl:NamedIndividual, c:Product .
f:NO a owl:NamedIndividual, i:ProcessOperation ; i:partOfProcess f:NP ; i:consumesEnergyKWh "10"^^xsd:decimal ; t:hasEmissionFactor f:NF .
f:NF a owl:NamedIndividual, t:ElectricityEmissionFactor ; t:factorValue "0.5"^^xsd:decimal ; t:factorUnit "kg CO2e/kWh"^^xsd:string .'''
 numeric=[('equivalent_energy',base+' f:NO i:consumesEnergyKWh "10.0"^^xsd:decimal .','VALID'),('equivalent_factor_value',base+' f:NF t:factorValue "0.50"^^xsd:decimal .','VALID'),('equivalent_preasserted_ghg',base+' f:NO e:hasGHGImpactKgCO2e "5"^^xsd:decimal, "5.0"^^xsd:decimal .','VALID'),('equivalent_output_quantity',base+' f:NLot i:producesQuantity "100.0"^^xsd:decimal .','VALID'),('zero_energy',base.replace('"10"','"0"'),'VALID'),('zero_factor',base.replace('"0.5"','"0"'),'VALID'),('conflicting_energy',base+' f:NO i:consumesEnergyKWh "20"^^xsd:decimal .','AMBIGUOUS_INPUT'),('conflicting_factor_value',base+' f:NF t:factorValue "0.7"^^xsd:decimal .','AMBIGUOUS_INPUT'),('two_factor_iris_equal_value',base+' f:NO t:hasEmissionFactor f:NF2 . f:NF2 a owl:NamedIndividual, t:ElectricityEmissionFactor ; t:factorValue "0.5"^^xsd:decimal ; t:factorUnit "kg CO2e/kWh"^^xsd:string .','AMBIGUOUS_INPUT'),('conflicting_preasserted_ghg',base+' f:NO e:hasGHGImpactKgCO2e "5"^^xsd:decimal, "6"^^xsd:decimal .','AMBIGUOUS_INPUT'),('preasserted_ghg_mismatch',base+' f:NO e:hasGHGImpactKgCO2e "999"^^xsd:decimal .','NOT_EVALUABLE'),('negative_energy',base.replace('"10"','"-1"'),'NOT_EVALUABLE'),('negative_factor',base.replace('"0.5"','"-1"'),'NOT_EVALUABLE'),('missing_energy',base.replace('i:consumesEnergyKWh "10"^^xsd:decimal ; ',''),'NOT_EVALUABLE'),('missing_factor_link',base.replace(' ; t:hasEmissionFactor f:NF',''),'NOT_EVALUABLE'),('missing_factor_value',base.replace('t:factorValue "0.5"^^xsd:decimal ; ',''),'NOT_EVALUABLE'),('missing_factor_unit',base.replace(' ; t:factorUnit "kg CO2e/kWh"^^xsd:string',''),'NOT_EVALUABLE'),('wrong_factor_unit',base.replace('"kg CO2e/kWh"','"kg CO2e/kg"'),'NOT_EVALUABLE')]
 for name,body,state in numeric:
  path=ttl('CNUM-'+name,body)
  if state=='AMBIGUOUS_INPUT':
   tests.append(dict(id='CNUM_'+name,configuration='integrated',files=tbox+[path],enabled_rules=['R01','R21'],expected_status='NOT_EVALUATED',expected_numeric_status=state,expected_owl_status='CONSISTENT',expected_failure_kind='AMBIGUOUS_NUMERIC_INPUT',case='Contradictory scoped input blocks numeric inference before SWRL; OWL consistency is reported separately'))
   continue
  expected_ghg=0 if name in ['zero_energy','zero_factor'] else 5
  assertion('CNUM_'+name,qbody('Q03')+'FILTER(?lot=f:NLot && ?ghgKgCO2e='+str(expected_ghg)+')',state=='VALID',files=tbox+[path],enabled_rules=['R01','R21'],expected_numeric_status=state,control='CNUM',case='Independent10kWh×0.5=5kgCO2e; equivalent literals count once; missing/mismatched values cannot create a complete partial lot total')
  if name=='equivalent_output_quantity':
   assertion('Q06_numeric_equivalent_quantity',qbody('Q06')+'FILTER(?lot=f:NLot && ?liters=100 && ?ghgKgCO2e=5 && ?kgCO2ePerL=0.05)',files=tbox+[path],enabled_rules=['R01','R21'],expected_numeric_status='VALID',case='100 and100.0 are one denominator and do not double the numerator')
 # Explicit100/100.0 and0.5/0.50: one operation,100kWh,50kgCO2e.
 equivalent100=base.replace('"10"','"100"')+' f:NO i:consumesEnergyKWh "100.0"^^xsd:decimal . f:NF t:factorValue "0.50"^^xsd:decimal .'
 isolated('CNUM_equivalent_100_and_factor',equivalent100,qbody('Q03')+'FILTER(?lot=f:NLot && ?energyKWh=100 && ?ghgKgCO2e=50)',True,['R01','R21'],expected_numeric_status='VALID',case='Numeric100/100.0 andfactor0.5/0.50 each denote one input value;100×0.5=50, not100 or200')
 # One good selected operation plus one incomplete selected operation is NOT
 # equivalent to a one-operation complete process.
 partial=base+' f:NLot i:hasActivity f:IncompleteOp . f:IncompleteOp a owl:NamedIndividual, i:ProcessOperation ; i:partOfProcess f:NP ; t:hasEmissionFactor f:NF .'
 isolated('CNUM_partial_lot_rejected',partial,qbody('Q03')+'FILTER(?lot=f:NLot)',False,['R01','R21'],expected_numeric_status='NOT_EVALUABLE',case='Missing energy on a selected operation suppresses the entire lot total; no silent partial sum')
 orphan=base+' f:Orphan a owl:NamedIndividual, i:ProcessOperation .'
 isolated('CNUM_orphan_outside_scope',orphan,qbody('Q03')+'FILTER(?lot=f:NLot && ?ghgKgCO2e=5)',True,['R01','R21'],expected_numeric_status='VALID',case='Incomplete unselected orphan does not invalidate another lot')
 equal=base+' f:NLot i:hasActivity f:NO2 . f:NO2 a owl:NamedIndividual, i:ProcessOperation ; i:partOfProcess f:NP ; i:consumesEnergyKWh "10.0"^^xsd:decimal ; t:hasEmissionFactor f:NF .'
 isolated('CNUM_distinct_operations_equal_contributions',equal,qbody('Q03')+'FILTER(?lot=f:NLot && ?energyKWh=20 && ?ghgKgCO2e=10)',True,['R01','R21'],expected_numeric_status='VALID',case='Two distinct operations each5kgCO2e produce10kgCO2e, neverSUM DISTINCT on values')
 foreign=base+' f:NLot i:hasActivity f:Foreign . f:Foreign a owl:NamedIndividual, i:ProcessOperation ; i:partOfProcess f:ForeignP ; i:consumesEnergyKWh "999"^^xsd:decimal . f:ForeignP a owl:NamedIndividual, i:ManufacturingProcess .'
 isolated('CNUM_foreign_operation_excluded',foreign,qbody('Q03')+'FILTER(?lot=f:NLot && ?ghgKgCO2e=5)',True,['R01','R21'],expected_numeric_status='VALID',expected_context_status='CONTEXT_INTEGRITY_ERROR',case='Foreign operation is visible in CCTX and excluded from the affected numeric scope')
 pair='''f:A a owl:NamedIndividual, i:Lot ; i:requiresCleaningBetween f:B ; i:processedOn f:M ; t:endTimeSeconds "100"^^xsd:decimal . f:B a owl:NamedIndividual, i:Lot ; i:processedOn f:M ; t:startTimeSeconds "200"^^xsd:decimal . f:M a owl:NamedIndividual, i:EquipmentResource . f:Clean a owl:NamedIndividual, i:CleaningOperation ; t:cleanedResource f:M ; t:startTimeSeconds "110"^^xsd:decimal ; t:endTimeSeconds "190"^^xsd:decimal .'''
 for name,extra,state in [('equivalent_end','f:A t:endTimeSeconds "100.0"^^xsd:decimal .','COMPLETE_CLEANING_RECORD'),('equivalent_start','f:B t:startTimeSeconds "200.0"^^xsd:decimal .','COMPLETE_CLEANING_RECORD'),('conflicting_end','f:A t:endTimeSeconds "150"^^xsd:decimal .','NOT_EVALUABLE'),('conflicting_start','f:B t:startTimeSeconds "250"^^xsd:decimal .','NOT_EVALUABLE'),('mixed_valid_invalid_end','f:A t:endTimeSeconds "300"^^xsd:decimal .','NOT_EVALUABLE')]:
  isolated('C26_contract_'+name,pair+' '+extra,ADDITIONAL_CONTROLS['C26'][5:-2],state=='NOT_EVALUABLE','NONE',expected_cleaning_status=state,case='A single numeric endpoint per lot: equivalent representations accepted; every contradictory extreme rejects the pair even when another combination fits the cleaning')
 # Every common resource requires its own record; an unshared resource does not.
 two=pair+' f:A i:processedOn f:M2 . f:B i:processedOn f:M2 . f:M2 a owl:NamedIndividual, i:EquipmentResource .'
 from build_catalog import VALIDATIONS
 isolated('C26_two_common_equipment_one_missing',two,VALIDATIONS['R26'][5:-2],True,'NONE',expected_cleaning_status='MISSING_CLEANING_RECORD',case='Record for M does not cover second shared equipment M2')
 two+=' f:Clean2 a owl:NamedIndividual, i:CleaningOperation ; t:cleanedResource f:M2 ; t:startTimeSeconds "110"^^xsd:decimal ; t:endTimeSeconds "190"^^xsd:decimal .'
 isolated('C26_two_common_equipment_complete',two,VALIDATIONS['R26'][5:-2],False,'NONE',expected_cleaning_status='COMPLETE_CLEANING_RECORD',case='Separate cleaning records cover both common equipment resources')
 isolated('C26_unshared_equipment_ignored',pair+' f:A i:processedOn f:M2 . f:M2 a owl:NamedIndividual, i:EquipmentResource .',VALIDATIONS['R26'][5:-2],False,'NONE',expected_cleaning_status='COMPLETE_CLEANING_RECORD',case='Equipment absent from the next lot does not require an inter-lot cleaning record')
